import type { ProtocolFlow } from '@/types'

export const CORE_PROTOCOL: ProtocolFlow = {
  id: 'lucy-core-v1',
  name: 'Temel Protokol',
  description: 'Benliğin mimarisine yapılandırılmış bir yolculuk.',
  version: '1.0.0',
  entryNodeId: 'entry',
  metadata: {
    estimatedMinutes: 12,
    theme: 'self-inquiry',
    tags: ['kimlik', 'desen', 'farkındalık', 'bilinç'],
  },
  nodes: {
    entry: {
      id: 'entry',
      type: 'transition',
      content: 'Başlamadan önce — bir nefes al.',
      subtext: 'Bu alan senin. Yanlış cevap yok. Sadece şu an doğru olan var.',
      nextNodeId: 'q_present',
      depthLevel: 0,
    },
    q_present: {
      id: 'q_present',
      type: 'question',
      questionType: 'open',
      content: 'Seni tam olarak bu ana, buraya ne getirdi?',
      subtext: 'Hikâyeyi değil. Altındaki hissi.',
      nextNodeId: 'q_resistance',
      depthLevel: 1,
      tags: ['presence', 'motivation'],
    },
    q_resistance: {
      id: 'q_resistance',
      type: 'question',
      questionType: 'choice',
      content: 'Zor bir şeyle karşılaştığında ilk hareketin ne olur?',
      depthLevel: 1,
      tags: ['pattern', 'coping'],
      choices: [
        { id: 'r1', label: 'Üzerine yürürüm', nextNodeId: 'q_lean_in', tags: ['approach'], weight: 1 },
        { id: 'r2', label: 'Geri çekilip gözlemlerim', nextNodeId: 'q_observer', tags: ['dissociation', 'wisdom'], weight: 1 },
        { id: 'r3', label: 'Etrafından dolaşırım', nextNodeId: 'q_avoidance', tags: ['avoidance'], weight: 1 },
        { id: 'r4', label: 'İçinde erir giderim', nextNodeId: 'q_merger', tags: ['merger', 'overwhelm'], weight: 1 },
      ],
    },
    q_lean_in: {
      id: 'q_lean_in',
      type: 'question',
      questionType: 'open',
      content: 'Zorluğun üzerine yürüyorsun. O zor şeyin içinde ne arıyorsun?',
      subtext: 'Kanıt mı? Çözüm mü? Hâlâ sen olduğunun kanıtı mı?',
      nextNodeId: 'q_identity_anchor',
      depthLevel: 2,
      tags: ['approach', 'identity'],
    },
    q_observer: {
      id: 'q_observer',
      type: 'question',
      questionType: 'open',
      content: 'İzliyorsun. Kendini nereden gözlemliyorsun?',
      subtext: 'Göreni bul.',
      nextNodeId: 'q_identity_anchor',
      depthLevel: 2,
      tags: ['meta-awareness', 'dissociation'],
    },
    q_avoidance: {
      id: 'q_avoidance',
      type: 'question',
      questionType: 'open',
      content: 'Etrafından dolaştığın yol — seni neyi bilmekten koruyor?',
      subtext: 'Burada yargı yok. Sadece merak var.',
      nextNodeId: 'q_identity_anchor',
      depthLevel: 2,
      tags: ['avoidance', 'protection'],
    },
    q_merger: {
      id: 'q_merger',
      type: 'question',
      questionType: 'open',
      content: 'Eridiğinde — seninle zorluk arasındaki sınır nereye gidiyor?',
      subtext: 'Kenarlar yok olduğunda ne kalıyor?',
      nextNodeId: 'q_identity_anchor',
      depthLevel: 2,
      tags: ['merger', 'boundaries'],
    },
    q_identity_anchor: {
      id: 'q_identity_anchor',
      type: 'question',
      questionType: 'open',
      content: 'Bu cümleyi tamamla: Ben her zaman ___ biri/biriyim',
      subtext: 'İlk gelen şey. Düşünülmüş olan değil.',
      nextNodeId: 'q_identity_contradiction',
      depthLevel: 2,
      tags: ['identity', 'self-concept'],
    },
    q_identity_contradiction: {
      id: 'q_identity_contradiction',
      type: 'question',
      questionType: 'binary',
      content: 'Az önce yazdığın... gerçek mi? Yoksa o kadar çok anlattın ki gerçekmiş gibi hissettiren bir hikâye mi?',
      depthLevel: 3,
      tags: ['identity', 'narrative', 'truth'],
      choices: [
        { id: 'c1', label: 'Gerçekten doğru', nextNodeId: 'q_truth_source', tags: ['certainty'] },
        { id: 'c2', label: 'Bir hikâye olabilir', nextNodeId: 'q_story_origin', tags: ['questioning'] },
      ],
    },
    q_truth_source: {
      id: 'q_truth_source',
      type: 'question',
      questionType: 'open',
      content: 'Nasıl biliyorsun? Bunun sadece tekrarlanmış değil, gerçek olduğunun kanıtı ne?',
      nextNodeId: 'q_pattern_recognition',
      depthLevel: 3,
      tags: ['epistemology', 'evidence'],
    },
    q_story_origin: {
      id: 'q_story_origin',
      type: 'question',
      questionType: 'open',
      content: 'O hikâye ne zaman başladı? İlk kim anlattı — sen mi, yoksa başkası mı?',
      nextNodeId: 'q_pattern_recognition',
      depthLevel: 3,
      tags: ['origin', 'narrative'],
    },
    q_pattern_recognition: {
      id: 'q_pattern_recognition',
      type: 'question',
      questionType: 'scale',
      content: 'Şu anki hayatının ne kadarı, artık var olmayan bir sen tarafından alınan kararlarla şekillendi?',
      subtext: 'Eski bir sen seçimler yaptı. Şimdi onların içinde yaşıyorsun.',
      nextNodeId: 'q_change_resistance',
      depthLevel: 3,
      scaleMin: 1,
      scaleMax: 10,
      scaleLabels: ['Neredeyse hiç', 'Neredeyse her şey'],
      tags: ['pattern', 'legacy', 'past-self'],
    },
    q_change_resistance: {
      id: 'q_change_resistance',
      type: 'question',
      questionType: 'choice',
      content: 'Gerçekten farklı biri olmayı hayal ettiğinde — içinde ne doğuyor?',
      depthLevel: 3,
      tags: ['change', 'resistance', 'identity'],
      choices: [
        { id: 'ch1', label: 'Heyecan', nextNodeId: 'q_deep_desire', tags: ['openness'] },
        { id: 'ch2', label: 'Bir şeyi kaybetme korkusu', nextNodeId: 'q_loss_fear', tags: ['attachment'] },
        { id: 'ch3', label: 'Uyuşukluk', nextNodeId: 'q_numbness', tags: ['dissociation'] },
        { id: 'ch4', label: 'İzin verilmediği hissi', nextNodeId: 'q_permission', tags: ['permission', 'restriction'] },
      ],
    },
    q_deep_desire: {
      id: 'q_deep_desire',
      type: 'question',
      questionType: 'open',
      content: 'Tam olarak var olmasına hiç izin vermediğin sen hangisi?',
      subtext: 'Hedeflenen sen değil. Bastırılan sen.',
      nextNodeId: 'breath_1',
      depthLevel: 4,
      tags: ['shadow', 'suppression', 'potential'],
    },
    q_loss_fear: {
      id: 'q_loss_fear',
      type: 'question',
      questionType: 'open',
      content: 'Farklı biri olsaydın tam olarak ne kaybolurdu? Yumuşatmadan adını koy.',
      nextNodeId: 'breath_1',
      depthLevel: 4,
      tags: ['loss', 'attachment', 'identity-cost'],
    },
    q_numbness: {
      id: 'q_numbness',
      type: 'question',
      questionType: 'open',
      content: 'Uyuşukluğun altında — konuşabilseydi — değişim hakkında ne söylerdi?',
      subtext: 'Uyuşukluk yokluk değil. Korumadır. Neyi koruyor?',
      nextNodeId: 'breath_1',
      depthLevel: 4,
      tags: ['numbness', 'protection', 'emotion'],
    },
    q_permission: {
      id: 'q_permission',
      type: 'question',
      questionType: 'open',
      content: 'Kimin iznini hâlâ bekliyorsun?',
      subtext: 'Çoktan gitmiş olabilirler. Kapı hayali olabilir.',
      nextNodeId: 'breath_1',
      depthLevel: 4,
      tags: ['permission', 'authority', 'freedom'],
    },
    breath_1: {
      id: 'breath_1',
      type: 'question',
      questionType: 'breath',
      content: 'Burada dur.',
      subtext: '4 sayı nefes al. 4 tut. 6\'da bırak.',
      nextNodeId: 'q_core_wound',
      breathDuration: 14000,
      depthLevel: 4,
    },
    q_core_wound: {
      id: 'q_core_wound',
      type: 'question',
      questionType: 'open',
      content: 'Tüm kalıpların, savunmaların ve stratejilerin bir şeye cevapsa — o şey ne?',
      subtext: 'Mükemmel şekilde adlandırmak zorunda değilsin. Yaklaştır.',
      nextNodeId: 'q_reframe',
      depthLevel: 4,
      tags: ['core', 'wound', 'origin'],
    },
    q_reframe: {
      id: 'q_reframe',
      type: 'question',
      questionType: 'open',
      content: 'Ya o şey — az önce adını koyduğun şey — bir yara değil de bir harita olsaydı?',
      subtext: 'Neyin önemli olduğunun kaydı. Dikkat ettiğinin kanıtı.',
      nextNodeId: 'insight_1',
      depthLevel: 4,
      tags: ['reframe', 'meaning', 'integration'],
    },
    insight_1: {
      id: 'insight_1',
      type: 'insight',
      content: 'Vajra cevap desenlerini işliyor.',
      subtext: 'Bu an entegre ediliyor.',
      nextNodeId: 'q_emergence',
      depthLevel: 4,
    },
    q_emergence: {
      id: 'q_emergence',
      type: 'question',
      questionType: 'open',
      content: 'Bu seansta yüzeye çıkan her şeyden — artık bilmiyormuş gibi yapmaya razı olmadığın tek şey ne?',
      depthLevel: 5,
      nextNodeId: 'terminus',
      tags: ['integration', 'emergence', 'commitment'],
    },
    terminus: {
      id: 'terminus',
      type: 'terminus',
      content: 'Protokol tamamlandı.',
      subtext: 'Buraya getirdiğin şey kalır. Keşfettiğin şey — artık senin.',
      depthLevel: 5,
    },
  },
}

export const ALL_FLOWS: Record<string, ProtocolFlow> = {
  [CORE_PROTOCOL.id]: CORE_PROTOCOL,
}
