import type { ProtocolFlow } from '@/types'

export const CORE_PROTOCOL: ProtocolFlow = {
  id: 'lucy-core-v1',
  name: 'The Core Protocol',
  description: 'A structured journey through the architecture of self.',
  version: '1.0.0',
  entryNodeId: 'entry',
  metadata: {
    estimatedMinutes: 12,
    theme: 'self-inquiry',
    tags: ['identity', 'pattern', 'awareness', 'consciousness'],
  },
  nodes: {
    entry: {
      id: 'entry',
      type: 'transition',
      content: 'Before we begin — take a breath.',
      subtext: 'This space is yours. There are no wrong answers. Only what is true right now.',
      nextNodeId: 'q_present',
      depthLevel: 0,
    },
    q_present: {
      id: 'q_present',
      type: 'question',
      questionType: 'open',
      content: 'What brought you here, to this exact moment?',
      subtext: 'Not the story. The feeling beneath it.',
      nextNodeId: 'q_resistance',
      depthLevel: 1,
      tags: ['presence', 'motivation'],
    },
    q_resistance: {
      id: 'q_resistance',
      type: 'question',
      questionType: 'choice',
      content: 'When you face something difficult, what is your first move?',
      depthLevel: 1,
      tags: ['pattern', 'coping'],
      choices: [
        { id: 'r1', label: 'I move toward it', nextNodeId: 'q_lean_in', tags: ['approach'], weight: 1 },
        { id: 'r2', label: 'I step back to observe', nextNodeId: 'q_observer', tags: ['dissociation', 'wisdom'], weight: 1 },
        { id: 'r3', label: 'I find ways around it', nextNodeId: 'q_avoidance', tags: ['avoidance'], weight: 1 },
        { id: 'r4', label: 'I dissolve into it', nextNodeId: 'q_merger', tags: ['merger', 'overwhelm'], weight: 1 },
      ],
    },
    q_lean_in: {
      id: 'q_lean_in',
      type: 'question',
      questionType: 'open',
      content: 'You move toward difficulty. What are you searching for inside the hard thing?',
      subtext: 'Is it proof? Resolution? Proof that you are still you?',
      nextNodeId: 'q_identity_anchor',
      depthLevel: 2,
      tags: ['approach', 'identity'],
    },
    q_observer: {
      id: 'q_observer',
      type: 'question',
      questionType: 'open',
      content: 'You watch. From where do you observe yourself?',
      subtext: 'Locate the one who sees.',
      nextNodeId: 'q_identity_anchor',
      depthLevel: 2,
      tags: ['meta-awareness', 'dissociation'],
    },
    q_avoidance: {
      id: 'q_avoidance',
      type: 'question',
      questionType: 'open',
      content: 'The path around it — what does it protect you from having to know?',
      subtext: 'There is no judgment here. Only curiosity.',
      nextNodeId: 'q_identity_anchor',
      depthLevel: 2,
      tags: ['avoidance', 'protection'],
    },
    q_merger: {
      id: 'q_merger',
      type: 'question',
      questionType: 'open',
      content: 'When you dissolve — where does the boundary between you and the difficulty go?',
      subtext: 'What remains when the edges are gone?',
      nextNodeId: 'q_identity_anchor',
      depthLevel: 2,
      tags: ['merger', 'boundaries'],
    },
    q_identity_anchor: {
      id: 'q_identity_anchor',
      type: 'question',
      questionType: 'open',
      content: 'Finish this sentence: I am someone who always ___',
      subtext: 'The first thing. Not the considered thing.',
      nextNodeId: 'q_identity_contradiction',
      depthLevel: 2,
      tags: ['identity', 'self-concept'],
    },
    q_identity_contradiction: {
      id: 'q_identity_contradiction',
      type: 'question',
      questionType: 'binary',
      content: 'Is what you just wrote... true? Or is it a story you have told so many times it became true?',
      depthLevel: 3,
      tags: ['identity', 'narrative', 'truth'],
      choices: [
        { id: 'c1', label: 'It is genuinely true', nextNodeId: 'q_truth_source', tags: ['certainty'] },
        { id: 'c2', label: 'It might be a story', nextNodeId: 'q_story_origin', tags: ['questioning'] },
      ],
    },
    q_truth_source: {
      id: 'q_truth_source',
      type: 'question',
      questionType: 'open',
      content: 'How do you know? What is the evidence that this is real, not just repeated?',
      nextNodeId: 'q_pattern_recognition',
      depthLevel: 3,
      tags: ['epistemology', 'evidence'],
    },
    q_story_origin: {
      id: 'q_story_origin',
      type: 'question',
      questionType: 'open',
      content: 'When did that story begin? Who told it first — you, or someone else?',
      nextNodeId: 'q_pattern_recognition',
      depthLevel: 3,
      tags: ['origin', 'narrative'],
    },
    q_pattern_recognition: {
      id: 'q_pattern_recognition',
      type: 'question',
      questionType: 'scale',
      content: 'How much of your current life is shaped by decisions made by a version of you that no longer exists?',
      subtext: 'A previous self made choices. You are living inside them.',
      nextNodeId: 'q_change_resistance',
      depthLevel: 3,
      scaleMin: 1,
      scaleMax: 10,
      scaleLabels: ['Almost none', 'Almost everything'],
      tags: ['pattern', 'legacy', 'past-self'],
    },
    q_change_resistance: {
      id: 'q_change_resistance',
      type: 'question',
      questionType: 'choice',
      content: 'When you imagine becoming someone genuinely different — what arises?',
      depthLevel: 3,
      tags: ['change', 'resistance', 'identity'],
      choices: [
        { id: 'ch1', label: 'Excitement', nextNodeId: 'q_deep_desire', tags: ['openness'] },
        { id: 'ch2', label: 'Fear of losing something', nextNodeId: 'q_loss_fear', tags: ['attachment'] },
        { id: 'ch3', label: 'Numbness', nextNodeId: 'q_numbness', tags: ['dissociation'] },
        { id: 'ch4', label: 'A feeling it is not allowed', nextNodeId: 'q_permission', tags: ['permission', 'restriction'] },
      ],
    },
    q_deep_desire: {
      id: 'q_deep_desire',
      type: 'question',
      questionType: 'open',
      content: 'What is the version of yourself you have never allowed to exist fully?',
      subtext: 'Not the aspirational self. The suppressed one.',
      nextNodeId: 'breath_1',
      depthLevel: 4,
      tags: ['shadow', 'suppression', 'potential'],
    },
    q_loss_fear: {
      id: 'q_loss_fear',
      type: 'question',
      questionType: 'open',
      content: 'What specifically would be lost if you became different? Name it without softening.',
      nextNodeId: 'breath_1',
      depthLevel: 4,
      tags: ['loss', 'attachment', 'identity-cost'],
    },
    q_numbness: {
      id: 'q_numbness',
      type: 'question',
      questionType: 'open',
      content: 'Underneath the numbness — if it could speak — what would it say about change?',
      subtext: 'Numbness is not absence. It is protection. What is it protecting?',
      nextNodeId: 'breath_1',
      depthLevel: 4,
      tags: ['numbness', 'protection', 'emotion'],
    },
    q_permission: {
      id: 'q_permission',
      type: 'question',
      questionType: 'open',
      content: 'Whose permission are you still waiting for?',
      subtext: 'They may be long gone. The gate may be imaginary.',
      nextNodeId: 'breath_1',
      depthLevel: 4,
      tags: ['permission', 'authority', 'freedom'],
    },
    breath_1: {
      id: 'breath_1',
      type: 'question',
      questionType: 'breath',
      content: 'Pause here.',
      subtext: 'Breathe in for 4 counts. Hold for 4. Release for 6.',
      nextNodeId: 'q_core_wound',
      breathDuration: 14000,
      depthLevel: 4,
    },
    q_core_wound: {
      id: 'q_core_wound',
      type: 'question',
      questionType: 'open',
      content: 'If all your patterns, defenses, and strategies are responses to something — what is that something?',
      subtext: 'You do not have to name it perfectly. Approximate it.',
      nextNodeId: 'q_reframe',
      depthLevel: 4,
      tags: ['core', 'wound', 'origin'],
    },
    q_reframe: {
      id: 'q_reframe',
      type: 'question',
      questionType: 'open',
      content: 'What if that thing — the thing you just named — was not a wound, but a map?',
      subtext: 'A record of what mattered. Evidence that you were paying attention.',
      nextNodeId: 'insight_1',
      depthLevel: 4,
      tags: ['reframe', 'meaning', 'integration'],
    },
    insight_1: {
      id: 'insight_1',
      type: 'insight',
      content: 'Lucy is processing your response patterns.',
      subtext: 'This moment is being integrated.',
      nextNodeId: 'q_emergence',
      depthLevel: 4,
    },
    q_emergence: {
      id: 'q_emergence',
      type: 'question',
      questionType: 'open',
      content: 'From everything surfaced in this session — what is one thing you are no longer willing to pretend you do not know?',
      depthLevel: 5,
      nextNodeId: 'terminus',
      tags: ['integration', 'emergence', 'commitment'],
    },
    terminus: {
      id: 'terminus',
      type: 'terminus',
      content: 'The Protocol is complete.',
      subtext: 'What you brought here remains. What you discovered — that is yours now.',
      depthLevel: 5,
    },
  },
}

export const ALL_FLOWS: Record<string, ProtocolFlow> = {
  [CORE_PROTOCOL.id]: CORE_PROTOCOL,
}
